% -------------------------------------------------------------------------
% EXAMPLE 5 -- Halley fractal of x^3 - 1 with relaxation parameter of 2.
% -------------------------------------------------------------------------

margin = struct('bottom', -0.9, ...
                   'top',  0.9, ...
                  'left', -0.9, ...
                 'right',  0.9);

% Custom colormap
cmap = [200, 200, 255;
         80,  80, 220;
          0,   0,   0;
          0,   0,   0]/255;
            
opts = struct('margin', margin, ...
             'maxIter', 75,     ...
                 'tol', 0.001,  ...
              'height', 1000,   ...
           'smoothing', true,   ...
                   'r', 2,      ...
                'cmap', cmap);

workingDir = '~/Example5/';

syms x

halleyFractal(x^3 - 1, workingDir, opts);